// Champions hold items from smogon/damage-calc master ITEMS[0].
export const CHAMPIONS_ITEMS = [
  'Abomasite',
  'Absolite',
  'Aerodactylite',
  'Aggronite',
  'Alakazite',
  'Altarianite',
  'Ampharosite',
  'Aspear Berry',
  'Audinite',
  'Babiri Berry',
  'Banettite',
  'Barbaracite',
  'Beedrillite',
  'Big Root',
  'Black Belt',
  'Black Glasses',
  'Blastoisinite',
  'Blazikenite',
  'Bright Powder',
  'Cameruptite',
  'Chandelurite',
  'Charcoal',
  'Charizardite X',
  'Charizardite Y',
  'Charti Berry',
  'Cheri Berry',
  'Chesnaughtite',
  'Chesto Berry',
  'Chilan Berry',
  'Chimechite',
  'Choice Scarf',
  'Chople Berry',
  'Clefablite',
  'Coba Berry',
  'Colbur Berry',
  'Crabominite',
  'Damp Rock',
  'Delphoxite',
  'Dragalgite',
  'Dragon Fang',
  'Dragoninite',
  'Drampanite',
  'Eelektrossite',
  'Emboarite',
  'Excadrite',
  'Expert Belt',
  'Fairy Feather',
  'Falinksite',
  'Feraligite',
  'Floettite',
  'Focus Band',
  'Focus Sash',
  'Froslassite',
  'Galladite',
  'Garchompite',
  'Gardevoirite',
  'Gengarite',
  'Glalitite',
  'Glimmoranite',
  'Golurkite',
  'Greninjite',
  'Gyaradosite',
  'Haban Berry',
  'Hard Stone',
  'Hawluchanite',
  'Heat Rock',
  'Heracronite',
  'Houndoominite',
  'Icy Rock',
  'Iron Ball',
  'Kangaskhanite',
  'Kasib Berry',
  'Kebia Berry',
  "King's Rock",
  'Leftovers',
  'Leppa Berry',
  'Life Orb',
  'Light Ball',
  'Light Clay',
  'Lopunnite',
  'Lucarionite',
  'Lum Berry',
  'Magnet',
  'Malamarite',
  'Manectite',
  'Mawilite',
  'Medichamite',
  'Meganiumite',
  'Mental Herb',
  'Meowsticite',
  'Metal Coat',
  'Metagrossite',
  'Metronome',
  'Miracle Seed',
  'Muscle Band',
  'Mystic Water',
  'Never-Melt Ice',
  'Occa Berry',
  'Oran Berry',
  'Passho Berry',
  'Payapa Berry',
  'Pecha Berry',
  'Persim Berry',
  'Pidgeotite',
  'Pinsirite',
  'Poison Barb',
  'Pyroarite',
  'Quick Claw',
  'Raichunite X',
  'Raichunite Y',
  'Rawst Berry',
  'Rindo Berry',
  'Roseli Berry',
  'Sablenite',
  'Sceptilite',
  'Scizorite',
  'Scolipite',
  'Scope Lens',
  'Scovillainite',
  'Scraftinite',
  'Sharp Beak',
  'Sharpedonite',
  'Shed Shell',
  'Shell Bell',
  'Shuca Berry',
  'Silk Scarf',
  'Silver Powder',
  'Sitrus Berry',
  'Skarmorite',
  'Slowbronite',
  'Smooth Rock',
  'Soft Sand',
  'Spell Tag',
  'Staraptite',
  'Starminite',
  'Steelixite',
  'Swampertite',
  'Tanga Berry',
  'Twisted Spoon',
  'Tyranitarite',
  'Venusaurite',
  'Victreebelite',
  'Wacan Berry',
  'White Herb',
  'Wide Lens',
  'Wise Glasses',
  'Yache Berry',
  'Zoom Lens',
] as const;
